variable "vsphere_server" {}
variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_datacenter" {}
variable "vsphere_datastore" {}
variable "vsphere_compute_cluster" {}
variable "vsphere_network" {}
variable "vsphere_virtual_machine" {}
variable "domain_user" {}
variable "domain_password" {}
variable "domain_add_domain" {}
variable "domain_add_user" {}
variable "domain_add_password" {}
variable "customize_company_name" {}
variable "customize_local_admin_pwd" {}